name: Swift Build

on:
  push:
    branches: [ "main", "Collaboration" ]
  pull_request:
    branches: [ "main", "Collaboration" ]
permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Build
      working-directory: ios
      run: swift build -v

    - name: Run tests
      working-directory: ios
      run: swift test -v
