name: Swift Build

on:
  push:
    branches: [ "main", "Collaboration" ]
  pull_request:
    branches: [ "main", "Collaboration" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        - swift build -v
    - name: package
      run: |
        - package.swift -v
    - name: Run tests
      run: |
        - swift test -v
